import { describe, expect, it } from "vitest";
import { replayLeadEvents, type TandemEvent } from "./domain.js";
import { replayLeadEvents as replayV01, type TandemEvent as EventV01, type LeadState as StateV01 } from "./fixtures/domain-0.1.fixture.js";

// Invariant 1 of docs/design-0.2-lifetime-commission.md: every history the
// 0.1 reducer accepted must replay to the same result in 0.2. Histories are
// generated by a seeded random walk that only keeps events the 0.1 reducer
// accepts, then every prefix is compared field by field.

function rng(seed: number) {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 0x100000000;
  };
}

const W = "w", L = "lead";
const DAY = 86_400_000;
const T0 = Date.UTC(2026, 0, 1);

function candidates(rand: () => number, t: number, state: StateV01 | null): { type: string; data: unknown }[] {
  const amount = [100, 999, 10_000, 250_001][Math.floor(rand() * 4)];
  const at = (offsetDays: number) => new Date(t + offsetDays * DAY).toISOString();
  const payment = state?.payment?.amountMinor ?? 10_000;
  return [
    { type: "lead.assigned", data: { agentId: "agent-1", territoryId: rand() < 0.5 ? null : "t-1" } },
    { type: "lead.lost", data: { reason: "no budget" } },
    { type: "lead.stage_changed", data: { salesStage: ["Contacted", "Qualified", "Closed_Won"][Math.floor(rand() * 3)] } },
    { type: "conversion.confirmed", data: {} },
    { type: "payment.confirmed", data: { amountMinor: amount, currency: "MYR" } },
    { type: "payment.refunded", data: { reason: "customer refund" } },
    { type: "commission.held", data: { payoutId: "p1", partnerId: "partner-1", amountMinor: Math.max(1, Math.floor(payment / 10)), currency: "MYR", releaseAt: at(rand() < 0.5 ? 0 : 3) } },
    { type: "commission.eligible", data: { payoutId: "p1" } },
    { type: "commission.approved", data: { payoutId: "p1" } },
    { type: "commission.paid", data: { payoutId: "p1", payoutReference: "ref-1" } },
    { type: "commission.voided", data: { payoutId: "p1", reason: "fraud" } },
    { type: "commission.adjusted", data: { payoutId: "p1", newAmountMinor: Math.max(1, Math.floor(payment / 20)) } },
    { type: "commission.reinstated", data: { payoutId: "p1", amountMinor: Math.max(1, Math.floor(payment / 15)), releaseAt: at(2) } },
    { type: "commission.clawback_requested", data: { payoutId: "p1", amountMinor: 1, reason: "dispute upheld" } },
  ];
}

function comparable(s: StateV01 | null) {
  if (!s) return null;
  return {
    status: s.status, salesStage: s.salesStage, companyName: s.companyName, qualificationMetric: s.qualificationMetric,
    partnerId: s.partnerId, agentId: s.agentId, territoryId: s.territoryId, lastSequence: s.lastSequence,
    payment: s.payment,
    commission: s.commission && {
      payoutId: s.commission.payoutId, partnerId: s.commission.partnerId, amountMinor: s.commission.amountMinor,
      currency: s.commission.currency, releaseAt: s.commission.releaseAt, status: s.commission.status,
      clawback: s.commission.clawback && { amountMinor: s.commission.clawback.amountMinor, reason: s.commission.clawback.reason, requestedAt: s.commission.clawback.requestedAt },
    },
  };
}

describe("0.1 compatibility", () => {
  it("replays thousands of random valid 0.1 histories to the same state after every event", () => {
    let histories = 0, compared = 0, moneyHistories = 0;
    for (let seed = 1; seed <= 3000; seed++) {
      const rand = rng(seed);
      const events: EventV01[] = [];
      let t = T0;
      const push = (type: string, data: unknown) => {
        const e = { id: `e${events.length + 1}`, sequence: events.length + 1, workspaceId: W, leadId: L, source: "test", sourceEventId: `s${events.length + 1}`, occurredAt: new Date(t).toISOString(), type, data } as EventV01;
        try {
          replayV01([...events, e], W, L);
          events.push(e);
          return true;
        } catch {
          return false;
        }
      };
      push("lead.created", { companyName: "Acme", qualificationMetric: 5, qualification: rand() < 0.5 ? "Automated_Setup" : "Manual_Review", partnerId: "partner-1" });
      for (let step = 0; step < 40; step++) {
        t += Math.floor(rand() * 5) * DAY;
        const options = candidates(rand, t, replayV01(events, W, L));
        const pick = options[Math.floor(rand() * options.length)];
        push(pick.type, pick.data);
      }
      histories++;
      if (events.some((e) => e.type === "commission.paid" || e.type === "payment.refunded")) moneyHistories++;
      for (let n = 1; n <= events.length; n++) {
        const prefix = events.slice(0, n);
        const expected = comparable(replayV01(prefix, W, L));
        const actual = comparable(replayLeadEvents(prefix as unknown as TandemEvent[], W, L) as unknown as StateV01);
        expect(actual).toEqual(expected);
        compared++;
      }
    }
    expect(histories).toBe(3000);
    // The walk must actually reach the money paths, or this test proves nothing.
    expect(moneyHistories).toBeGreaterThan(500);
    expect(compared).toBeGreaterThan(20_000);
  });
});
